[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lyrionRemote"
version = "0.1.0"  # Set your static version here directly
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" } # Standard PEP 621 format for simple licenses
keywords = ['lyrion', 'lms', 'gpio', 'remote']
authors = [
  { name = "rawdlite", email = "rawdlite@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  'gpiozero',
  'pigpio',
  'pigpio-encoder',
  'luma.core',
  'luma.oled',
  "pytest>=8.3.5",
  "requests>=2.32.4",
]

[project.urls]
Documentation = "https://github.com/rawdlite/lyrion-remote#readme"
Issues = "https://github.com/rawdlite/lyrion-remote/issues"
Source = "https://github.com/rawdlite/lyrion-remote"

# Setuptools automatically discovers anything inside the src/ directory
[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
lmscommander = "lyrionRemote.cli:main"
gpiocontroller = "lyrionRemote.gpiocontrol:main"

[tool.coverage.run]
source_pkgs = ["lyrionRemote", "tests"]
branch = true
parallel = true
omit = [
  "src/lyrionRemote/__about__.py",
]

[tool.coverage.paths]
lyrionRemote = ["src/lyrionRemote", "*/lyrion-remote/src/lyrionRemote"]
tests = ["tests", "*/lyrion-remote/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

